backend:
  name: git-gateway
  branch: main
media_folder: "images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "cakes" # Used in routes, e.g., /admin/collections/blog
    label: "Cakes" # Used in the UI
    folder: "cakes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Short description",
          name: "description",
          widget: "string",
          hint:"The short blurb that will appear on the home page",
        }
      - { label: "Client", name: "client", widget: "string", required:false }
      - {
          label: "Testimonial",
          name: "quote",
          widget: "string",
          required: false,
          hint: "Optional, you can come back and add this later",
        }
      - {
          label: "Longer description",
          name: "body",
          widget: "text",
          hint:"This is the longer text that appears on the individual cake page",
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          allow_add:true,
          field: { label: Image, name: image, widget: image },
        }
# default: you may specify a list of strings to populate the basic text field, or an array of list items for lists using the fields option. If no default is declared when using field or fields, will default to a single list item using the defaults on the child widgets
# allow_add: false hides the button to add additional items
# collapsed: when true, the entries collapse by default
# summary: specify the label displayed on collapsed entries
# minimize_collapsed: when true, collapsing the list widget will hide all of it's entries instead of showing summaries
# label_singular: the text to show on the add button
# field: a single widget field to be repeated
# fields: a nested list of multiple widget fields to be included in each repeatable iteration
# max: maximum number of items in the list
# min: minimum number of items in the list
# add_to_top: when true, new entries will be added to the top of the list
