backend:
    name: git-gateway
    branch: main
media_folder: "images"

collections:
    - name: "cakes"
      label: "Cake"
      folder: "cakes"
      create: true
      fields:
          - { label: "Date", name: "date", widget: "datetime" }
          - {
                label: "Short description",
                name: "description",
                widget: "string",
                hint:"The short blurb that will appear on the home page",
            }
          - {
                label: "Longer description",
                name: "body",
                widget: "text",
                hint:"Longer text that appears on the individual cake page",
            }
          - {
                label: "Images",
                name: "images",
                widget: "list",
                allow_add:true,
                collapsed:false,
                min: 1,
                field: { label: Image, name: image, widget: image },
            }
          - {
                label: "Client",
                name: "client",
                widget: "string",
                required: false,
                hint:'First name and last initial',
            }
          - {
                label: "Testimonial",
                name: "quote",
                widget: "string",
                required: false,
                hint: "You can come back and add this later",
            }
