backend:
  name: git-gateway
  branch: main
media_folder: "images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "cakes" # Used in routes, e.g., /admin/collections/blog
    label: "Cake" # Used in the UI
    folder: "cakes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Short description",
          name: "description",
          widget: "string",
          hint:"The short blurb that will appear on the home page",
        }
      - {
          label: "Longer description",
          name: "body",
          widget: "text",
          hint:"This is the longer text that appears on the individual cake page",
        }
      - {
          label: "Images",
          name: "images",
          widget: "list",
          allow_add:true,
          collapsed:false,
          field: { label: Image, name: image, widget: image },
        }
      - {
          label: "Client",
          name: "client",
          widget: "string",
          required:false,
          hint:'First name and last initial',
        }
      - {
          label: "Testimonial",
          name: "quote",
          widget: "string",
          required: false,
          hint: "Optional, you can come back and add this later",
        }
